Controlsys.Interfaces/Controllers/InfracaoController.cs
using Controlsys.Dominio.Parametros;
using Controlsys.Infra;
using Controlsys.Interfaces.Models;
using Controlsys.Repositorio.Parametros;
using Controlsys.Repositorios.Parametros;
using Globalsys;
using Globalsys.Validacao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Controlsys.Interfaces.Controllers
{
    [ExtendController]
    public class InfracaoController : Controller, IControllerBase
    {

        public IUnidadeTrabalho UnidadeTrabalho { get; set; }

        public InfracaoController(IUnidadeTrabalho unidadeTrabalho)
        {
            UnidadeTrabalho = unidadeTrabalho;
        }

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Inclui um novo infracao.
        /// </summary>
        ///
        /// <param name="infracao">
        /// O(a) infracao.
        /// </param>
        ///
        /// <returns>
        /// Um(a) ActionResult.
        /// </returns>
        [Transaction]
        public ActionResult Incluir(Infracao infracao)
        {
            IRepositorioInfracao repInfracao = Fabrica.Instancia.ObterRepositorio<IRepositorioInfracao>(UnidadeTrabalho);
            infracao.DataRegistro = DateTime.Now;
            infracao.Ativar();
            repInfracao.Validar(infracao, EstadoObjeto.Novo);
            repInfracao.Salvar(infracao);
            return Json(new InfracaoModelView { Ativo = infracao.Ativo, Codigo = infracao.Codigo, Grau = infracao.Grau.ObterDescricaoEnum(), Nome = infracao.Nome, Sigla = infracao.Sigla });

        }

        /// <summary>
        /// Altera um registro de infracao.
        /// </summary>
        ///
        /// <param name="infracao">
        /// O(a) infracao.
        /// </param>
        ///
        /// <returns>
        /// Um(a) ActionResult.
        /// </returns>
        [Transaction]
        public ActionResult Alterar(Infracao infracao)
        {
            IRepositorioInfracao repInfracao = Fabrica.Instancia.ObterRepositorio<IRepositorioInfracao>(UnidadeTrabalho);
            Infracao infracaoA = repInfracao.ObterPorId(infracao.Codigo);
            infracaoA.Grau = infracao.Grau;
            infracaoA.Nome = infracao.Nome;
            infracaoA.Sigla = infracao.Sigla;
            repInfracao.Validar(infracaoA, EstadoObjeto.Alterado);
            repInfracao.Atualizar(infracaoA);

            return Json(new InfracaoModelView { Ativo = infracaoA.Ativo, Codigo = infracaoA.Codigo, Grau = infracaoA.Grau.ObterDescricaoEnum(), Nome = infracaoA.Nome, Sigla = infracaoA.Sigla });
        }

        /// <summary>
        /// Ativar inativar.
        /// </summary>
        ///
        /// <param name="codigo">
        /// O(a) codigo.
        /// </param>
        ///
        /// <returns>
        /// Um(a) ActionResult.
        /// </returns>
        [Transaction]
        public ActionResult AtivarInativar(int codigo)
        {
            IRepositorioInfracao repInfracao = Fabrica.Instancia.ObterRepositorio<IRepositorioInfracao>(UnidadeTrabalho);
            Infracao infracao = repInfracao.ObterPorId(codigo);
            if (infracao.Ativo)
            {
                repInfracao.Validar(infracao, EstadoObjeto.Inativado);
                infracao.Inativar();
            }
            else
            {
                repInfracao.Validar(infracao, EstadoObjeto.Ativado);
                infracao.Ativar();
            }
            repInfracao.Atualizar(infracao);
            return Json(new InfracaoModelView()
            {
                Codigo = infracao.Codigo,
                Nome = infracao.Nome,
                Sigla = infracao.Sigla,
                Grau = infracao.Grau.ObterDescricaoEnum(),
                Ativo = infracao.Ativo
            });
            //return Json(infracao);
        }

        /// <summary>
        /// Selecionar.
        /// </summary>
        ///
        /// <param name="codigo">
        /// O(a) codigo.
        /// </param>
        ///
        /// <returns>
        /// Um(a) ActionResult.
        /// </returns>
        public ActionResult Selecionar(int codigo)
        {
            IRepositorioInfracao repInfracao = Fabrica.Instancia.ObterRepositorio<IRepositorioInfracao>(UnidadeTrabalho);
            Infracao infracao = repInfracao.ObterPorId(codigo);
            return Json(infracao);
        }

        /// <summary>
        /// Retorna todos os objetos do tipo infracao.
        /// </summary>
        ///
        /// <param name="apenasAtivos">
        /// true to apenas ativos.
        /// </param>
        ///
        /// <returns>
        /// Detalhes do tipo de objeto ligado ao controller no formato JSON.
        /// </returns>
        public ActionResult ObterTodos(bool apenasAtivos = false)
        {
            IRepositorioInfracao repInfracao = Fabrica.Instancia.ObterRepositorio<IRepositorioInfracao>(UnidadeTrabalho);

            IQueryable<Infracao> infracoes = repInfracao.ObterTodos();

            if (apenasAtivos)
            {
                infracoes = infracoes.Where(t => t.Ativo == true);
            }

            return Json(infracoes.ToList().Select(i => new InfracaoModelView()
            {
                Codigo = i.Codigo,
                Nome = i.Nome,
                Sigla = i.Sigla,
                Grau = i.Grau.ObterDescricaoEnum(),
                Ativo = i.Ativo
            }).ToList().OrderBy(i => i.Nome));
        }

        public ActionResult ObterGrausInfracao()
        {
            Dictionary<int, string> dic = new Dictionary<int, string>();

            foreach (int item in Enum.GetValues(typeof(GrauInfracao)))
            {
                dic.Add(item, ((GrauInfracao)item).ObterDescricaoEnum());
            }

            return Json(dic.Select(d => new
            {
                Codigo = d.Key,
                Descricao = d.Value
            }).ToList());
        }


    }
}

Controlsys.Interfaces/Views/Infracao/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">

    function cancelar() {
        App.frmInfracao.form.reset();
    }

    function salvar() {

        if (App.frmInfracao.isValid()) {
            var infracao = App.frmInfracao.form.getValues();
            if (!infracao.Codigo) {
                Globalsys.Util.request({
                    url: '@Url.Action("Incluir", "Infracao")',
                    params: {
                        infracao: infracao
                    },
                    success: function (response, opts) {
                        App.grdInfracao.store.add(response);
                        App.grdInfracao.store.commitChanges();
                        App.frmInfracao.form.reset();
                        Ext.Msg.show({ title: 'Confirmação', icon: Ext.MessageBox.INFO, msg: 'Registro incluído com sucesso.', buttons: Ext.Msg.OK });
                    }

                });
            } else {
                Globalsys.Util.request({
                    url: '@Url.Action("Alterar", "Infracao")',
                    params: {
                        infracao: infracao
                    },
                    success: function (response, opts) {
                        Globalsys.Util.updateModel(App.grdInfracao, response);
                        App.frmInfracao.form.reset();
                        Ext.Msg.show({ title: 'Confirmação', icon: Ext.MessageBox.INFO, msg: 'Registro alterado com sucesso.', buttons: Ext.Msg.OK });
                    }
                });
            }
        } else {

            Ext.Msg.show({ title: 'Atenção', icon: Ext.MessageBox.WARNING, msg: 'Não é possível salvar. O formulário possui campos não preenchidos.', buttons: Ext.Msg.OK });
        }
    }

    var commandInfracao = function (command, record) {

        var codigo = record.data.Codigo;

        if (command == "AlterarStatus") {
            Globalsys.Util.request({
                url: '@Url.Action("AtivarInativar", "Infracao")',
                params: {
                    codigo: codigo
                },
                success: function (response, opts) {
                    Globalsys.Util.updateModel(App.grdInfracao, response);

                }
            });
        }
        if (command == "Selecionar") {

            Globalsys.Util.request({
                url: '@Url.Action("Selecionar", "Infracao")',
                params: {
                    codigo: codigo
                },
                success: function (response, opts) {
                    App.frmInfracao.form.setValues(response);
                }
            });
        }
    };


    var prepareStatus = function (v, metaData) {
        if (v) {
            metaData.style = 'background-color : Green; color: White;';
            return metaData.column.trueText;
        } else {
            metaData.style = 'background-color : Red; color: White;';
            return metaData.column.falseText;
        }
    };

    var alteraIcon = function (grid, toolbar, rowIndex, record) {
        var statusButton = toolbar.items.get(1);

        if (record.data.Ativo) {
            statusButton.setIconCls("#Delete");
        }
        else {
            statusButton.setIconCls("#Accept");
        }
    };

</script>

@(Html.X().Viewport().Layout(LayoutType.Fit).Items(
    Html.X().Panel(new Panel { Border = false, Title = "INFRAÇÃO", Icon = Icon.ApplicationForm }).LayoutConfig(new VBoxLayoutConfig { Align = VBoxAlign.Stretch, Pack = BoxPack.Start }).Items(
        Html.X().FormPanel(new FormPanel { Border = false, Title = "CADASTRO", Icon = Icon.Add, ID = "frmInfracao", Collapsible = true }).LayoutConfig(new VBoxLayoutConfig { Align = VBoxAlign.Stretch, Pack = BoxPack.Start }).Items(
            Html.X().Panel().Border(false).Flex(1).BodyPadding(5).LayoutConfig(new HBoxLayoutConfig { Align = HBoxAlign.Stretch, Pack = BoxPack.Start }).Items(
                Html.X().TextField(new TextField()
                {
                    ID = "txtCodigo",
                    Name = "Codigo",
                    Hidden = true
                }),
                Html.X().TextField(new TextField()
                {
                    ID = "txtSigla",
                    FieldLabel = "Sigla",
                    LabelWidth = 35,
                    Name = "Sigla",
                    Flex = 1,
                    AllowBlank = false,
                    IndicatorText = "*",
                    StyleSpec = "color: red; font-weight: bold; margin-right: 10px;",
                    IndicatorTip = "Campo requerido.",
                    EmptyText = "Sigla"
                }),
                Html.X().TextField(new TextField()
                {
                    ID = "txtDescricao",
                    FieldLabel = "Descrição",
                    LabelWidth = 65,
                    Name = "Nome",
                    Flex = 3,
                    AllowBlank = false,
                    IndicatorText = "*",
                    StyleSpec = "color: red; font-weight: bold; margin-right: 10px;",
                    IndicatorTip = "Campo requerido.",
                    EmptyText = "Descrição"
                }),
                Html.X().ComboBox(new ComboBox()
                        {
                            ID = "cmbTipoGravidade",
                            FieldLabel = "Gravidade",
                            Flex = 2,
                            LabelWidth = 65,
                            ForceSelection = true,
                            TypeAhead = true, 
                            EmptyText = "Grau",
                            AllowBlank = false,
                            Name = "Grau",
                            IndicatorText = "*",
                            StyleSpec = "color: red; font-weight: bold;",
                            IndicatorTip = "Campo requerido."
                        }).QueryMode(DataLoadMode.Local)
                                                    .DisplayField("Descricao")
                                                    .ValueField("Codigo")
                                                    .Store(Html.X().Store()
                                                            .Model(Html.X().Model()
                                                                .IDProperty("Id")
                                                                .Fields(
                                                                    new ModelField("Codigo", ModelFieldType.Int) { Mapping = "Codigo" },
                                                                    new ModelField("Descricao", ModelFieldType.String) { Mapping = "Descricao" }
                                                                ))
                                                            .Proxy(Html.X().AjaxProxy(new AjaxProxy { Url = Url.Action("ObterGrausInfracao", "Infracao") })
                                                                                .Reader(new JsonReader { Root = "Data" })))
                )).BottomBar(
                    Html.X().Toolbar().Items(
                        Html.X().Button(new Button { Text = "Salvar", Icon = Icon.Disk }).Listeners(p => p.Click.Handler = "salvar()"),
                        Html.X().Button(new Button { Text = "Cancelar", Icon = Icon.Cancel }).Listeners(p => p.Click.Handler = "cancelar()"))),
            Html.X().Panel(new Panel() { Border = false, Title = "LISTA", Icon = Icon.Table, Flex = 1 }).LayoutConfig(new VBoxLayoutConfig { Align = VBoxAlign.Stretch, Pack = BoxPack.Start }).Items(
                Html.X().GridPanel().ID("grdInfracao").Flex(1).Store(
                    Html.X().Store().AutoLoad(true).Proxy(
                        Html.X().AjaxProxy(new AjaxProxy { Url = Url.Action("ObterTodos", "Infracao")}).Reader(new JsonReader { Root = "Data"})).ID("strInfracao").PageSize(14).RemotePaging(false).Model(
                            Html.X().Model().IDProperty("Codigo").Fields(
                                Html.X().ModelField().Name("Codigo"),
                                Html.X().ModelField().Name("Sigla").Type(ModelFieldType.String),
                                Html.X().ModelField().Name("Nome").Type(ModelFieldType.String),
                                Html.X().ModelField().Name("Grau").Type(ModelFieldType.String),
                                Html.X().ModelField().Name("Ativo").Type(ModelFieldType.Boolean)))).ColumnModel(
                                    Html.X().CommandColumn().Width(50).PrepareToolbar("alteraIcon").Commands(
                                        Html.X().GridCommand().CommandName("Selecionar").Icon(Icon.NoteEdit),
                                        Html.X().GridCommand().CommandName("AlterarStatus").Icon(Icon.Accept)).Listeners(a => a.Command.Handler = "commandInfracao(command,record);"),
                                        Html.X().Column().Text("Sigla").DataIndex("Sigla").Flex(1),
                                        Html.X().Column().Text("Descrição").DataIndex("Nome").Flex(3),
                                        Html.X().Column().Text("Gravidade").DataIndex("Grau").Flex(1),
                                        Html.X().BooleanColumn().FalseText("INATIVO").TrueText("ATIVO").Text("Status").DataIndex("Ativo").Renderer("prepareStatus").HeaderItems(
                                            Html.X().TextField().ID("StatusFilter").Listeners(l => { l.Change.Handler = "applyFilter(this);"; }))).Plugins(
                                                Html.X().FilterHeader()).BottomBar(
                                                    Html.X().PagingToolbar().HideRefresh(true)))))
)