Controlsys.Interfaces/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Controlsys.Dominio.Empresas;
using Controlsys.Infra;
using Controlsys.Repositorios.Parametros;
using Ext.Net;
using Ext.Net.MVC;
using Globalsys;
using Ninject;
using Globalsys.Exceptions;
using Globalsys.Validacao;

namespace Controlsys.Interfaces.Controllers
{
    /// <summary>
    /// Um controlador para tratar areas.
    /// </summary>
    [ExtendController]
    public class AreaController : Controller, IControllerBase
    {
        /// <summary>
        /// GET: /Area/.
        /// </summary>
        ///
        /// <value>
        /// Retorna o(a) UnidadeTrabalho.
        /// </value>
        public IUnidadeTrabalho UnidadeTrabalho { get; set; }

        /// <summary>
        /// Construtor para Controlsys.Interfaces.Controllers.AreaController.
        /// </summary>
        ///
        /// <param name="unidade">
        /// O(a) unidade.
        /// </param>
        public AreaController(IUnidadeTrabalho unidade)
        {
            UnidadeTrabalho = unidade;
        }

        /// <summary>
        /// Retorna a página de area.
        /// </summary>
        ///
        /// <returns>
        /// Um(a) ActionResult.
        /// </returns>
        [ExcludeFromCodeCoverage]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Inclui um novo area.
        /// </summary>
        ///
        /// <param name="area">
        /// O(a) area.
        /// </param>
        ///
        /// <returns>
        /// Um(a) ActionResult.
        /// </returns>
        [Transaction]
        public ActionResult Incluir(Area area)
        {
            IRepositorioArea repArea = Fabrica.Instancia.ObterRepositorio<IRepositorioArea>(UnidadeTrabalho);
            area.DataRegistro = DateTime.Now;
            area.Ativar();   
            repArea.Validar(area, EstadoObjeto.Novo);
            repArea.Salvar(area);
            return Json(area);

        }

        /// <summary>
        /// Altera um registro de area.
        /// </summary>
        ///
        /// <param name="area">
        /// O(a) area.
        /// </param>
        ///
        /// <returns>
        /// Um(a) ActionResult.
        /// </returns>
        [Transaction]
        public ActionResult Alterar(Area area)
        {
            IRepositorioArea repArea = Fabrica.Instancia.ObterRepositorio<IRepositorioArea>(UnidadeTrabalho);
            Area areaA = repArea.ObterPorId(area.Codigo);
            areaA.Numero = area.Numero;
            areaA.Nome = area.Nome;
            repArea.Validar(areaA, EstadoObjeto.Alterado);
            repArea.Atualizar(areaA);
            return Json(areaA);
        }

        /// <summary>
        /// Ativar inativar.
        /// </summary>
        ///
        /// <param name="codigo">
        /// O(a) codigo.
        /// </param>
        ///
        /// <returns>
        /// Um(a) ActionResult.
        /// </returns>
        [Transaction]
        public ActionResult AtivarInativar(int codigo)
        {
            IRepositorioArea repArea = Fabrica.Instancia.ObterRepositorio<IRepositorioArea>(UnidadeTrabalho);
            Area area = repArea.ObterPorId(codigo);       
            if (area.Ativo)
            {
                area.Inativar();
            }
            else
            {
                repArea.Validar(area, EstadoObjeto.Ativado);
                area.Ativar();               
            }
            repArea.Atualizar(area);
            return Json(area);
        }

        /// <summary>
        /// Selecionar.
        /// </summary>
        ///
        /// <param name="codigo">
        /// O(a) codigo.
        /// </param>
        ///
        /// <returns>
        /// Um(a) ActionResult.
        /// </returns>
        public ActionResult Selecionar(int codigo)
        {
            IRepositorioArea repArea = Fabrica.Instancia.ObterRepositorio<IRepositorioArea>(UnidadeTrabalho);
            Area area = repArea.ObterPorId(codigo);
            return Json(area);
        }

        /// <summary>
        /// Retorna todos os objetos do tipo Area.
        /// </summary>
        ///
        /// <param name="apenasAtivos">
        /// true to apenas ativos.
        /// </param>
        ///
        /// <returns>
        /// Detalhes do tipo de objeto ligado ao controller no formato JSON.
        /// </returns>
        public ActionResult ObterTodos(bool apenasAtivos = false, string nome = "")
        {
            IRepositorioArea repArea = Fabrica.Instancia.ObterRepositorio<IRepositorioArea>(UnidadeTrabalho);

            IQueryable<Area> areas = repArea.ObterTodos();

            if (apenasAtivos)
                areas = areas.Where(t => t.Ativo == true);

            if (!string.IsNullOrEmpty(nome))
                areas = areas.Where(a => a.Nome.Contains(nome));

            return Json(areas.Select(a => new
                                {
                                    a.Codigo,
                                    a.Nome,
                                    a.Numero,
                                    a.Ativo
                                }).OrderBy(a => a.Nome)
                                .ToList());
        }

    }
}

Controlsys.Interfaces/Views/Area/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">

    function cancelar() {
        App.frmArea.form.reset();
    }

    function salvar() {

        if (App.frmArea.isValid()) {
            var area = App.frmArea.form.getValues();
            if (!area.Codigo) {
                Globalsys.Util.request({
                    url: '@Url.Action("Incluir", "Area")',
                    params: {
                        area: area
                    },
                    success: function (response, opts) {
                        App.grdArea.store.add(response);
                        App.grdArea.store.commitChanges();
                        App.frmArea.form.reset();
                        Ext.Msg.show({ title: 'Confirmação', icon: Ext.MessageBox.INFO, msg: 'Registro incluído com sucesso.', buttons: Ext.Msg.OK });
                    }

                });
            } else {
                Globalsys.Util.request({
                    url: '@Url.Action("Alterar", "Area")',
                        params: {
                            area: area
                        },
                        success: function (response, opts) {
                            Globalsys.Util.updateModel(App.grdArea, response);
                            App.frmArea.form.reset();
                            Ext.Msg.show({ title: 'Confirmação', icon: Ext.MessageBox.INFO, msg: 'Registro alterado com sucesso.', buttons: Ext.Msg.OK });
                        }
                    });
                }
            } else {

                Ext.Msg.show({ title: 'Atenção', icon: Ext.MessageBox.WARNING, msg: 'Não é possível salvar. O formulário possui campos não preenchidos.', buttons: Ext.Msg.OK });
            }
        }

        var commandArea = function (command, record) {

            var codigo = record.data.Codigo;

            if (command == "AlterarStatus") {

                Globalsys.Util.request({
                    url: '@Url.Action("AtivarInativar", "Area")',
                    params: {
                        codigo: codigo
                    },
                    success: function (response, opts) {
                        Globalsys.Util.updateModel(App.grdArea, response);

                    }
                });
            }
            if (command == "Selecionar") {

                Globalsys.Util.request({
                    url: '@Url.Action("Selecionar", "Area")',
                params: {
                    codigo: codigo
                },
                success: function (response, opts) {
                    App.frmArea.form.setValues(response);
                }
            });
        }
        };


    var prepareStatus = function (v, metaData) {
        if (v) {
            metaData.style = 'background-color : Green; color: White;';
            return metaData.column.trueText;
        } else {
            metaData.style = 'background-color : Red; color: White;';
            return metaData.column.falseText;
        }
    };

    var alteraIcon = function (grid, toolbar, rowIndex, record) {
        var statusButton = toolbar.items.get(1);

        if (record.data.Ativo) {
            statusButton.setIconCls("#Delete");
        }
        else {
            statusButton.setIconCls("#Accept");
        }
    };

</script>

@(Html.X().Viewport()
        //.Border(false)
    .Layout(LayoutType.Fit)
    .Items(Html.X().Panel(new Panel
    {
        Border = false,
        Title = "ÁREA",
        Icon = Icon.ApplicationForm
    })
        .LayoutConfig(new VBoxLayoutConfig
        {
            Align = VBoxAlign.Stretch,
            Pack = BoxPack.Start
        })
        .Items(Html.X().FormPanel(new FormPanel
        {
            Border = false,
            Title = "CADASTRO",
            Icon = Icon.Add,
            ID = "frmArea",
            Collapsible = true
        })
            .LayoutConfig(new VBoxLayoutConfig
            {
                Align = VBoxAlign.Stretch,
                Pack = BoxPack.Start
            })
            .Items(Html.X().Panel()
                .Border(false)
                .Flex(1)
                .BodyPadding(5)
                .LayoutConfig(new HBoxLayoutConfig
                {
                    Align = HBoxAlign.Stretch,
                    Pack = BoxPack.Start
                })
                .Items(Html.X().TextField(new TextField()
                {
                    ID = "txtCodigo",
                    Name = "Codigo",
                    Hidden = true,
                }),
                    Html.X().TextField(new TextField()
                    {
                        ID = "txtArea",
                        FieldLabel = "Área",
                        Name = "Nome",
                        Width = 300,
                        AllowBlank = false,
                        IndicatorText = "*",
                        StyleSpec = "color: red; font-weight: bold;",
                        IndicatorTip = "Campo requerido.",
                        EmptyText = "Área"

                    }), Html.X().TextField(new TextField()
                    {
                        ID = "txtNumero",
                        FieldLabel = "Número",
                        Name = "Numero",
                        Width = 250,
                        EmptyText = "Número"
                    })
                )
            ).BottomBar(Html.X().Toolbar()
                .Items(Html.X().Button(new Button
                {
                    Text = "Salvar",
                    Icon = Icon.Disk
                }).Listeners(p => p.Click.Handler = "salvar()"),
                    Html.X().Button(new Button
                    {
                        Text = "Cancelar",
                        Icon = Icon.Cancel
                    }).Listeners(p => p.Click.Handler = "cancelar()")
                )
            ),
            
            
            Html.X().Panel(new Panel()
            {
                Border = false,
                Title = "LISTA",
                Icon = Icon.Table,
                Flex = 1
            })
                .LayoutConfig(new VBoxLayoutConfig
                {
                    Align = VBoxAlign.Stretch,
                    Pack = BoxPack.Start
                })
                .Items(Html.X().GridPanel()
                .ID("grdArea")
                .Flex(1)
                .Store(Html.X().Store()
                    .AutoLoad(true)
                    .Proxy(Html.X().AjaxProxy(new AjaxProxy
                    {
                        Url = Url.Action("ObterTodos", "Area")
                    })
                        .Reader(new JsonReader
                        {
                            Root = "Data"
                        }))
                    .ID("strArea")
                    .PageSize(14)
                    .RemotePaging(false)
                    .Model(Html.X().Model().IDProperty("Codigo")
                        .Fields(
                            Html.X().ModelField().Name("Codigo"),
                            Html.X().ModelField().Name("Nome").Type(ModelFieldType.String),
                            Html.X().ModelField().Name("Numero").Type(ModelFieldType.String),
                            Html.X().ModelField().Name("Ativo").Type(ModelFieldType.Boolean)
                        )
                    )
                )
                .ColumnModel(
                    Html.X().CommandColumn()
                    .Width(50)
                    .PrepareToolbar("alteraIcon")
                    .Commands(
                        Html.X().GridCommand().CommandName("Selecionar").Icon(Icon.NoteEdit),
                        Html.X().GridCommand().CommandName("AlterarStatus").Icon(Icon.Accept)
                    ).Listeners(a => a.Command.Handler = "commandArea(command,record);"),
                    Html.X().Column().Text("Área").DataIndex("Nome").Flex(1),
                    Html.X().Column().Text("Número").DataIndex("Numero").Flex(1),
                    Html.X().BooleanColumn().FalseText("INATIVO").TrueText("ATIVO").Text("Status").DataIndex("Ativo").Renderer("prepareStatus")
                    .HeaderItems(Html.X().TextField()
                        .ID("StatusFilter")
                        .Listeners(l =>
                        {
                            l.Change.Handler = "applyFilter(this);";
                        }))
                )
                .Plugins(
                    Html.X().FilterHeader()
                )
                .BottomBar(
                    Html.X().PagingToolbar()
                    .HideRefresh(true)
                )
                
                
            )
        )
    )
)