Controlsys.Interfaces/Controllers/AlterarSenhaController.cs
using System.Diagnostics.CodeAnalysis;
using Controlsys.Dominio.Seguranca;
using Controlsys.Infra;
using Controlsys.Repositorios.Seguranca;
using Globalsys;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Controlsys.Interfaces.Controllers
{
    /// <summary>
    /// Um controlador para tratar alterar senhas.
    /// </summary>
    [ExtendController]
    public class AlterarSenhaController : Controller, IControllerBase
    {
        /// <summary>
        /// GET: /AlterarSenha/.
        /// </summary>
        ///
        /// <value>
        /// Retorna o(a) UnidadeTrabalho.
        /// </value>
        public IUnidadeTrabalho UnidadeTrabalho { get; set; }

        /// <summary>
        /// Construtor para Controlsys.Interfaces.Controllers.AlterarSenhaController.
        /// </summary>
        ///
        /// <param name="unidade">
        /// O(a) unidade.
        /// </param>
        public AlterarSenhaController(IUnidadeTrabalho unidade) { UnidadeTrabalho = unidade; }

        /// <summary>
        /// Retorna a página de alterarSenha.
        /// </summary>
        ///
        /// <returns>
        /// Um(a) ActionResult.
        /// </returns>
        [ExcludeFromCodeCoverage]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Altera um registro de alterarSenha.
        /// </summary>
        ///
        /// <param name="senhaNova">
        /// O(a) senha nova.
        /// </param>
        /// <param name="senhaNovaConf">
        /// O(a) senha nova conf.
        /// </param>
        /// <param name="senhaAtual">
        /// O(a) senha atual.
        /// </param>
        [Transaction]
        public void Alterar(string senhaNova, string senhaNovaConf, string senhaAtual)
        {
            IRepositorioUsuario repUsuario = Fabrica.Instancia.ObterRepositorio<IRepositorioUsuario>(UnidadeTrabalho);
            string userLogado = HttpContext.User.Identity.Name;
            Usuario user = repUsuario.AlterarSenha(userLogado, senhaNova, senhaNovaConf, senhaAtual);
            enviarEmail(user, senhaNova);
        }

        /// <summary>
        /// Enviar email.
        /// </summary>
        ///
        /// <param name="usuario">
        /// O(a) usuario.
        /// </param>
        /// <param name="senha">
        /// O(a) senha.
        /// </param>
        private void enviarEmail(Usuario usuario, string senha)
        {
            Dictionary<string, string> valoresSubs = new Dictionary<string, string>();

            valoresSubs.Add("$$Login$$", usuario.Login);
            valoresSubs.Add("$$Senha$$", senha);

            Globalsys.Util.Email.Enviar("[CONTROLSYS] - Dados de acesso",
                                        Server.MapPath("/Content/templates/alteracaoSenha.htm"),
                                        valoresSubs,
                                        string.Empty,
                                        null,
                                        usuario.PessoaFisica.Email);
        }
    }
}

Controlsys.Interfaces/Views/AlterarSenha/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>

    function cancelar() { App.frmAlterarSenha.form.reset(); }

    function salvar() {

        if (App.frmAlterarSenha.isValid()) {

            var senhaAtual = App.txtAtual.getValue();
            var senhaNova = App.txtNova.getValue();
            var senhaNovaConf = App.txtConfNova.getValue();
            if (senhaNova == senhaNovaConf) {

                Globalsys.Util.request({
                    url: '@Url.Action("Alterar", "AlterarSenha")',
                    params: {
                        senhaAtual: senhaAtual,
                        senhaNova: senhaNova,
                        senhaNovaConf: senhaNovaConf
                    },
                    success: function (response, opts) {
                        App.frmAlterarSenha.form.reset();
                        Ext.Msg.show({ title: 'Confirmação', icon: Ext.MessageBox.INFO, msg: 'Senha alterada com sucesso.', buttons: Ext.Msg.OK });
                    }
                });
            } else {
                Ext.Msg.show({ title: 'Atenção', icon: Ext.MessageBox.WARNING, msg: 'As senhas novas não correspondem. Tente novamente.', buttons: Ext.Msg.OK });
            }
        } else {
            Ext.Msg.show({ title: 'Atenção', icon: Ext.MessageBox.WARNING, msg: 'Não é possível salvar. O formulário possui campos não preenchidos.', buttons: Ext.Msg.OK });
        }
    }

</script>

@(Html.X().Viewport().Layout(LayoutType.Fit).Border(false)
            .Items(Html.X().Panel(new Panel()
            {
                Border = false,
                Layout = LayoutType.Fit.ToString()
            }
                    ).Items(Html.X().FormPanel(new FormPanel()
                    {
                        Title = "SENHA",
                        Icon = Icon.ApplicationForm,
                        AutoScroll = true
                    }
                        ).Items(Html.X().Panel(new Panel()
                        {
                            Border = false

                        }
                            ).Items(Html.X().FormPanel(new FormPanel()
                            {
                                Title = "ALTERAR SENHA",
                                ID = "frmAlterarSenha",
                                Icon = Icon.ArrowRefresh,
                                AutoScroll = true,
                                BodyPadding = 5,
                                BottomBar = {   Html.X().Toolbar().Items(
                                                    Html.X().Button().Text("Salvar").Icon(Icon.Disk).Handler("salvar();"),
                                                    Html.X().Button().Text("Cancelar").Icon(Icon.Cancel).Handler("cancelar();"))   
                                }
                            }).Items(Html.X().TextField(new TextField()
                                            {
                                                ID = "txtAtual",
                                                FieldLabel = "Senha Atual",
                                                Width = 300,
                                                Name = "SenhaAtual",
                                                InputType = Ext.Net.InputType.Password,
                                                AllowBlank = false,
                                                IndicatorText = "*",
                                                StyleSpec = "color: red; font-weight: bold;",
                                                IndicatorTip = "Campo requerido.",
                                                EmptyText = "Senha atual"

                                            }), Html.X().TextField(new TextField()
                                                {
                                                    ID = "txtNova",
                                                    FieldLabel = "Senha Nova",
                                                    Width = 300,
                                                    MinLength = 8,
                                                    Name = "SenhaNova",
                                                    InputType = Ext.Net.InputType.Password,
                                                    EmptyText = "Nova senha",
                                                    AllowBlank = false,
                                                    IndicatorText = "*",
                                                    StyleSpec = "color: red; font-weight: bold;",
                                                    IndicatorTip = "Campo requerido."

                                                }), Html.X().TextField(new TextField()
                                                {
                                                    ID = "txtConfNova",
                                                    FieldLabel = "Confirmar nova senha",
                                                    Width = 300,
                                                    MinLength = 8,
                                                    Name = "ConfimarSenhaNova",
                                                    InputType = Ext.Net.InputType.Password,
                                                    EmptyText = "Nova senha",
                                                    AllowBlank = false,
                                                    IndicatorText = "*",
                                                    StyleSpec = "color: red; font-weight: bold;",
                                                    IndicatorTip = "Campo requerido."

                                                }))
)))))