Controlsys.Interfaces/Controllers/TipoAlimentacaoController.cs
using Controlsys.Dominio.Parametros;
using Controlsys.Infra;
using Controlsys.Repositorio.Parametros;
using Globalsys;
using Globalsys.Validacao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Controlsys.Interfaces.Controllers
{

    [ExtendController]
    public class TipoAlimentacaoController : Controller, IControllerBase
    {
        /// <summary>
        /// GET: /Acao/.
        /// </summary>
        ///
        /// <value>
        /// Retorna o(a) UnidadeTrabalho.
        /// </value>
        public IUnidadeTrabalho UnidadeTrabalho { get; set; }

        /// <summary>
        /// Construtor para Controlsys.Interfaces.Controllers.AcaoController.
        /// </summary>
        ///
        /// <param name="unidadeTrabalho">
        /// O(a) unidade trabalho.
        /// </param>
        public TipoAlimentacaoController(IUnidadeTrabalho unidadeTrabalho)
        {
            UnidadeTrabalho = unidadeTrabalho;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ObterTodos(bool apenasAtivos = false, string descricao = null, int restaurante = 0)
        {
            IRepositorioTipoAlimentacao repTipoA = Fabrica.Instancia.ObterRepositorio<IRepositorioTipoAlimentacao>(UnidadeTrabalho);

            IQueryable<TipoAlimentacao> tiposA = repTipoA.ObterTodos();

            if (apenasAtivos)
                tiposA = tiposA.Where(t => t.Ativo == true);

           
            if (!string.IsNullOrEmpty(descricao))
                tiposA = tiposA.Where(ta => ta.Nome.ToLower().Contains(descricao.ToLower()));

            if (restaurante != 0)
            {
                IRepositorioRestaurante repRest = Fabrica.Instancia.ObterRepositorio<IRepositorioRestaurante>(UnidadeTrabalho);
                var rest = repRest.ObterPorId(restaurante).TiposAlimentacao.Where(r => r.Ativo);
                return Json(rest.Select(a => new
                {
                    a.TipoAlimentacao.Codigo,
                    a.TipoAlimentacao.Nome
                }).ToList());
            }

            tiposA = tiposA.OrderBy(ta => ta.Nome);

            return Json(tiposA.Select(a => new
            {
                a.Codigo,
                a.Nome,
                a.Ativo
            })
            .ToList());
        }

        [Transaction]
        public ActionResult Incluir(TipoAlimentacao tipoA)
        {
            IRepositorioTipoAlimentacao repTipoA = Fabrica.Instancia.ObterRepositorio<IRepositorioTipoAlimentacao>(UnidadeTrabalho);
            tipoA.DataRegistro = DateTime.Now;
            tipoA.Ativar();
            repTipoA.Validar(tipoA, EstadoObjeto.Novo);
            repTipoA.Salvar(tipoA);
            return Json(tipoA);
        }

        [Transaction]
        public ActionResult Alterar(TipoAlimentacao tipoA)
        {
            IRepositorioTipoAlimentacao repTipoA = Fabrica.Instancia.ObterRepositorio<IRepositorioTipoAlimentacao>(UnidadeTrabalho);
            TipoAlimentacao tipoAlimentacao = repTipoA.ObterPorId(tipoA.Codigo);
            tipoAlimentacao.Nome = tipoA.Nome;
            repTipoA.Validar(tipoAlimentacao, EstadoObjeto.Alterado);
            repTipoA.Atualizar(tipoAlimentacao);
            return Json(tipoAlimentacao);
        }

        [Transaction]
        public ActionResult AtivarInativar(int codigo)
        {
            IRepositorioTipoAlimentacao repTipoA = Fabrica.Instancia.ObterRepositorio<IRepositorioTipoAlimentacao>(UnidadeTrabalho);
            TipoAlimentacao tipoA = repTipoA.ObterPorId(codigo);
            if (tipoA.Ativo)
            {
                repTipoA.Validar(tipoA, EstadoObjeto.Inativado);
                tipoA.Inativar();
            }
            else
            {
                repTipoA.Validar(tipoA, EstadoObjeto.Ativado);
                tipoA.Ativar();
            }

            repTipoA.Atualizar(tipoA);
            return Json(tipoA);
        }

        public ActionResult Selecionar(int codigo)
        {
            IRepositorioTipoAlimentacao repTipoA = Fabrica.Instancia.ObterRepositorio<IRepositorioTipoAlimentacao>(UnidadeTrabalho);
            TipoAlimentacao tipoA = repTipoA.ObterPorId(codigo);
            return Json(tipoA);
        }

    }
}

Controlsys.Interfaces/Views/TipoAlimentacao/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">

    function cancelar() {
        App.frmTipoAlimentacao.form.reset();
    }

    function salvar() {

        if (App.frmTipoAlimentacao.isValid()) {
            var tipoA = App.frmTipoAlimentacao.form.getValues();
            if (!tipoA.Codigo) {
                Globalsys.Util.request({
                    url: '@Url.Action("Incluir", "TipoAlimentacao")',
                    params: {
                        tipoA: tipoA
                    },
                    success: function (response, opts) {
                        App.grdTipoAlimentacao.store.add(response);
                        App.grdTipoAlimentacao.store.commitChanges();
                        App.frmTipoAlimentacao.form.reset();
                        Ext.Msg.show({ title: 'Confirmação', icon: Ext.MessageBox.INFO, msg: 'Registro incluído com sucesso.', buttons: Ext.Msg.OK });
                    }

                });
            } else {
                Globalsys.Util.request({
                    url: '@Url.Action("Alterar", "TipoAlimentacao")',
                    params: {
                        tipoA: tipoA
                    },
                    success: function (response, opts) {
                        Globalsys.Util.updateModel(App.grdTipoAlimentacao, response);
                        App.frmTipoAlimentacao.form.reset();
                        Ext.Msg.show({ title: 'Confirmação', icon: Ext.MessageBox.INFO, msg: 'Registro alterado com sucesso.', buttons: Ext.Msg.OK });
                    }
                });
            }
        } else {

            Ext.Msg.show({ title: 'Atenção', icon: Ext.MessageBox.WARNING, msg: 'Não é possível salvar. O formulário possui campos não preenchidos.', buttons: Ext.Msg.OK });
        }
    }

    var commandTipoAlimentacao = function (command, record) {

        var codigo = record.data.Codigo;

        if (command == "AlterarStatus") {

            Globalsys.Util.request({
                url: '@Url.Action("AtivarInativar", "TipoAlimentacao")',
                    params: {
                        codigo: codigo
                    },
                    success: function (response, opts) {
                        Globalsys.Util.updateModel(App.grdTipoAlimentacao, response);

                    }
                });
            }
            if (command == "Selecionar") {

                Globalsys.Util.request({
                    url: '@Url.Action("Selecionar", "TipoAlimentacao")',
                    params: {
                        codigo: codigo
                    },
                    success: function (response, opts) {
                        App.frmTipoAlimentacao.form.setValues(response);
                    }
                });
            }
        };


        var prepareStatus = function (v, metaData) {
            if (v) {
                metaData.style = 'background-color : Green; color: White;';
                return metaData.column.trueText;
            } else {
                metaData.style = 'background-color : Red; color: White;';
                return metaData.column.falseText;
            }
        };

        var alteraIcon = function (grid, toolbar, rowIndex, record) {
            var statusButton = toolbar.items.get(1);

            if (record.data.Ativo) {
                statusButton.setIconCls("#Delete");
            }
            else {
                statusButton.setIconCls("#Accept");
            }
        };

</script>

@(Html.X().Viewport().Layout(LayoutType.Fit).Items(
    Html.X().Panel(new Panel { Border = false, Title = "TIPO DE ALIMENTAÇÃO", Icon = Icon.ApplicationForm }).LayoutConfig(new VBoxLayoutConfig { Align = VBoxAlign.Stretch, Pack = BoxPack.Start }).Items(
        Html.X().FormPanel(new FormPanel{Border = false, Title = "CADASTRO", Icon = Icon.Add, ID = "frmTipoAlimentacao", Collapsible = true }) .LayoutConfig(new VBoxLayoutConfig { Align = VBoxAlign.Stretch, Pack = BoxPack.Start }).Items(
            Html.X().Panel().Border(false).Flex(1).BodyPadding(5).LayoutConfig(new HBoxLayoutConfig { Align = HBoxAlign.Stretch, Pack = BoxPack.Start }).Items(
                Html.X().TextField(new TextField() { ID = "txtCodigo", Name = "Codigo", Hidden = true, }),
                Html.X().TextField(new TextField() { ID = "txtTipoAlimentacao", FieldLabel = "Tipo de Alimentação", LabelWidth = 130, Name = "Nome", Width = 400, AllowBlank = false, IndicatorText = "*", StyleSpec = "color: red; font-weight: bold;", IndicatorTip = "Campo requerido.", EmptyText = "Tipo de Alimentação"  }))).BottomBar(
                    Html.X().Toolbar().Items(
                        Html.X().Button(new Button { Text = "Salvar", Icon = Icon.Disk }).Listeners(p => p.Click.Handler = "salvar()"),
                        Html.X().Button(new Button { Text = "Cancelar", Icon = Icon.Cancel }).Listeners(p => p.Click.Handler = "cancelar()"))),
            Html.X().Panel(new Panel() { Border = false, Title = "LISTA", Icon = Icon.Table, Flex = 1 }).LayoutConfig(new VBoxLayoutConfig { Align = VBoxAlign.Stretch, Pack = BoxPack.Start }).Items(
                Html.X().GridPanel().ID("grdTipoAlimentacao").Flex(1).Store(
                    Html.X().Store().AutoLoad(true).Proxy(
                        Html.X().AjaxProxy(new AjaxProxy { Url = Url.Action("ObterTodos", "TipoAlimentacao")}).Reader(new JsonReader { Root = "Data"})).ID("strTipoAlimentacao").PageSize(14).RemotePaging(false).Model(
                            Html.X().Model().IDProperty("Codigo").Fields(
                                Html.X().ModelField().Name("Codigo"),
                                Html.X().ModelField().Name("Nome").Type(ModelFieldType.String),
                                Html.X().ModelField().Name("Ativo").Type(ModelFieldType.Boolean)))).ColumnModel(
                                    Html.X().CommandColumn().Width(50).PrepareToolbar("alteraIcon").Commands(
                                        Html.X().GridCommand().CommandName("Selecionar").Icon(Icon.NoteEdit),
                                        Html.X().GridCommand().CommandName("AlterarStatus").Icon(Icon.Accept)).Listeners(a => a.Command.Handler = "commandTipoAlimentacao(command,record);"),
                                        Html.X().Column().Text("Tipo de Alimentação").DataIndex("Nome").Flex(1),
                                        Html.X().BooleanColumn().FalseText("INATIVO").TrueText("ATIVO").Text("Status").DataIndex("Ativo").Renderer("prepareStatus").HeaderItems(
                                            Html.X().TextField().ID("StatusFilter").Listeners(l => { l.Change.Handler = "applyFilter(this);"; }))).Plugins(
                                                Html.X().FilterHeader()).BottomBar(
                                                    Html.X().PagingToolbar().HideRefresh(true)))))
)